% Script to plot the estimated gains from a format generated by pltcalsol.m
% pep/29Nov13

fname = '../Data/SB002_LBA_OUTER_SPREAD_1ch_8_convcalsol.bin.gains';
gtseries = load (fname);
t_first = gtseries(1,1);
num = mjdsec2datenum (t_first);
col = {'b*', 'm*', 'r*', 'k*', 'g*', 'y*', 'w*', 'c*'};

subplot (211);
antoff=23;
colind = 1;
for ant=2:96:576 % Plot only one antenna per station
	plot ((gtseries (:,1)-t_first)/86400.+num, gtseries (:,(antoff+ant)), char(col(colind)));
	hold on;
	colind = colind + 1;
end;
title ('Estimated calibrated antenna phases'); 
xlabel (sprintf ('UTC past %s', datestr(num, 1))); ylabel ('Phase (rad)');
axis tight; grid on;
datetick ('x', 13, 'keepticks'); % Print HH:MM:SS legend on the time axis.

subplot (212);
colind = 1;
for ant=3:96:576 % Plot only one antenna per station
	plot ((gtseries (:,1)-t_first)/86400.+num, gtseries (:,(antoff+ant)), char(col(colind)));
	hold on;
	colind = colind + 1;
end;
title ('Estimated calibrated antenna gains'); 
xlabel (sprintf ('UTC past %s', datestr(num, 1))); ylabel ('Amplitude (arbit)');
axis tight; grid on;
datetick ('x', 13, 'keepticks'); % Print HH:MM:SS legend on the time axis.

[pathstr, name, ext] = fileparts (fname);	
print (gcf, strcat (strrep (strcat (name, ext), '.', '_'), '.png'), '-dpng'); 
% print (gcf, '../SB002_LBA_OUTER_SPREAD_1ch_8_convcalsol.bin.gains.png', '-dpng');
