% Script to plot the phases generated by only point sources in a field.
% pep/04Feb14

npix = 256; % Map dimension
nfracvis = 0.8; % Fraction of visibilities sampled.
nvissamp = int32(nfracvis * npix *npix);
nptsrc = 10;
ptsrcamprng = [1, 10];
% ptsrcamp = ones (1, nptsrc); % All src with same amplitude;
ptsrcamp = ptsrcamprng(1)+(ptsrcamprng(2)-ptsrcamprng(1)).*rand (1, nptsrc);

map = zeros (npix);
xpos = int32(1 + (npix-1).*rand (1, nptsrc));
ypos = int32(1 + (npix-1).*rand (1, nptsrc));
for i = 1:nptsrc
  map(xpos(i), ypos(i)) = ptsrcamp(i);
end;

vis = fft2(map);

% Sampled visibility positions: Random sampling
xvis = int32(1 + (npix-1).*rand (1, nvissamp));
yvis = int32(1 + (npix-1).*rand (1, nvissamp));
sampvis = zeros (nvissamp, 1);
sampdis = zeros (nvissamp, 1);
viscen = npix/2; % Visibility plane center
for i = 1:nvissamp
  sampvis (i) = vis (xvis(i), yvis(i));
  sampdis (i) = sqrt(double ((xvis(i)-viscen).^2 + (yvis(i)-viscen).^2));
end;

% Plot phase as a function of visibility amplitude
vispwr = abs(sampvis);
[sortpwr, sortpwrind] = sort (vispwr, 1, 'ascend');
subplot (211); plot (abs(sampvis(sortpwrind)), '.');   ylabel ('Vis. amp');
subplot (212); plot (angle(sampvis(sortpwrind)), '.'); ylabel ('Vis. phase');
xlabel ('Visibility power');
samexaxis ('join', 'YLabelDistance' ,1.0);

% Plot phase as a function of visibility position from center.
figure;
[sortbline, sortblineind] = sort (sampdis, 1, 'ascend');
subplot (211); plot (abs(sampvis(sortblineind)), '.');   ylabel ('Vis. amp');
subplot (212); plot (angle(sampvis(sortblineind)), '.'); ylabel ('Vis. phase');
xlabel ('Bline length');
samexaxis ('join', 'YLabelDistance', 1.0);

% Regenerate map from sampled visibilities
%sampacm = zeros (npix);
%for i = 1:nvissamp
%	sampacm (
%end;
